function[outpars,outshft] = frealign_refine(first,last,inparms,raw_images,ref_vol)
%%%%
data_input = '13pf';
reference_vol = '13pf_r0.mrc';
parout = 'tmp.parout';
shftout = 'tmp.shftout';
parin = 'tmp.parin';

%%CONFIGURATION
    frealign_exe = '/Users/ekellogg1/src/frealign_v9.09/bin_OSX/frealign_v9.exe';
    mode = 1; FMAG = 'F'; FDEF = 'F'; FASTIG = 'F'; FPART = 'F'; FMATCH = 'F'; IFSC = 0;
    RO = 215; RI = 75; PIX = 1.32; MW = 12080; AmpC = 0.07; XSTD = -4; pbc = 80; DANG = 200; ITMAX = 200; 
    dstep = 1.32; target = 10; cs = 2.7; kV = 300;
    rref = 8.0; rlowref = 400; rclas = 8.0; rbf = 0.0;
%%
command = sprintf([frealign_exe ' << eot  \n' ...
    'M,' num2str(mode) ',' FMAG ',' FDEF ',' FASTIG ',' FPART ',0,F,F,F,' FMATCH ',' num2str(IFSC) ',F,0,1\n' ...
    num2str(RO) ',' num2str(RI) ',' num2str(PIX) ',' num2str(MW) ',' num2str(AmpC) ',' num2str(XSTD) ',' num2str(pbc) ',0.0,' num2str(DANG) ',' num2str(ITMAX) ',20\n'...
    '1,1,1,1,1\n' ...
     num2str(first) ',' num2str(last) '\n' ...
    '0\n' ...   
    '1.0,' num2str(dstep) ',' num2str(target) ',0.0,' num2str(cs) ',' num2str(kV) ',0.0,0.0\n' ...
    num2str(rref) ',' num2str(rlowref) ',' num2str(rref) ',' num2str(rclas) ', 100.0, ' num2str(rbf) '\n' ...
    raw_images '\n' ...
    data_input '_reproject_r' num2str(first) '.mrc\n' ...
    parin '\n' ...
    parout '\n' ...
    shftout '\n' ...
    '-100., 0., 0., 0., 0., 0., 0., 0.\n' ...
    reference_vol '\n' ...
    'dummy_weights\n'...
    'dummy_map1.mrc\n'...
    'dummy_map2.mrc\n'...
    'dummy_phasediffs\n'...
    'dummy_pointspread\n'...
    'eot\n']);
%num2str(psi) ',' num2str(theta) ',' num2str(phi) ',' num2str(shx) ',' num2str(shy) '\n' ...   
display(command)
fid = fopen(parin,'w');
inputparams = textread(inparms,'%s','delimiter','\n');
for(i = first:last)
   fprintf(fid,'%s\n',inputparams{i}) 
end
fclose(fid)
system(command)

outpars = {};
p = textread(parout,'%s','delimiter','\n');
c = 1;
for(i = 1:length(p))
   t = p{i};
   if( strcmp(t(1),'C') == 0 )
      outpars{c} = t;
      c=c+1;
   end
end

outshft = {};
c = 1;
p = textread(shftout,'%s','delimiter','\n');
for(i = 1:length(p))
    t = p{i};
    if(strcmp(t(1),'C') == 0)
        outshft{c} = t;
        c=c+1;
    end
end
end